---
{{ if eq .Values.env "dev" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "1.5Gi"
            requests:
              cpu: "25m"
              memory: "1Gi"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
{{ end }}
