---
{{ if eq .Values.env "dev" }}
apiVersion: v1
kind: Service
metadata:
  name: elastic-service
  namespace: dino-park
spec:
  selector:
    app: elastic
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: rest
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: nodes
{{ end }}
